### ISSUE TITLE
Stuck forever in "INFO:root:setting up ocr"

### ISSUE THREAD

**Issue by forest-jiang** [pd3f/pd3f#5]
Hi, after I did a couple of successful convert, the pd3f has ran into problem of getting stuck in "INFO:root:setting up ocr" forever. Even after I ran `docker-compose run --rm worker rqscheduler --host redis --burst`.

**Comment by jfilter** [comment]
Hey, I think there was a problem with the underlying image from ocrmypdf. I upgraded to a newer version in https://github.com/pd3f/pd3f/commit/c75a86c8e4d65cbd1af72286d261b5f31dd3b1d5 and it fixed it for me (I also has the same problem).
